### ISSUE TITLE
Syntax on CSS Selectors

### ISSUE THREAD

**Issue by gunavs** [learn-co-curriculum/phase-0-css-fundamentals#4]
### Canvas Link

https://learning.flatironschool.com/courses/5298/pages/css-fundamentals?module_item_id=363082

### Concern

When talking about descendant/child selectors etc, the convention still has to start with #.

Lessons have them like this. Makes it a bit confusing

article p {
  color: blue;
}

**Comment by professor-ben** [comment]
Hello,

The '#' symbol in CSS affects elements with the ID denoted by the hash. The syntax that you've specified here is for descendants; it will affect all "p" elements inside of "article" elements.

Child syntax uses the ">" symbol and only affects elements that are immediate descendants (i.e. one level below) the parent.

I hope this clears things up.

-Ben
